# Generated by Django 5.1.2 on 2024-10-26 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FurApp', '0002_signup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='signup',
            new_name='signupdb',
        ),
    ]
