# Generated by Django 5.1.2 on 2024-11-08 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FurApp', '0004_cartdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartdb',
            old_name='MRP',
            new_name='Price',
        ),
    ]
