# Generated by Django 5.1.2 on 2024-11-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FurApp', '0006_orderdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdb',
            name='Cart_Image',
            field=models.ImageField(blank=True, null=True, upload_to='cart img'),
        ),
    ]
